name: Band Staff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3632e'
    - '#f3cb59'
    - '#7fc3c2'
    - '#333333'
    - '#008096'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
