name: Band Staff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8690d1'
    - '#1f1a17'
    - '#d7d9ef'
    - '#6b6e97'
    - '#b7b5b5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
