name: Band Staff
favicon: null
layout_spectrum: 0.6578345978632569
typography_spectrum: 0.7367495035286993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3632e'
    - '#f3cb59'
    - '#7fc3c2'
    - '#333333'
    - '#008096'
  brandStrength: 0.6052023256197572
  lightness: 0.8521615054924041
  saturation: 0.5678869844414294
  rhythmicContrast: 0.22537411423400044
purpose: []
